# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetShop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'ImageSlideshow', '~> 1.4'
pod "ImageSlideshow/SDWebImage"
pod 'Alamofire', '~> 4.7'
pod 'SVProgressHUD', '~> 2.2'
#pod 'SDWebImage', '~> 5.0'


end
